[package]
name = "{{.BotName}}"
version = "0.1.0"
edition = "2021"

[dependencies]
telegram-bot = "0.8"
tokio = { version = "0.2", features = ["full"]}
futures = "0.3.21"
botway-rs = "0.2"

[[bin]]
name = "bot"
path = "src/main.rs"
